server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/along_oa?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: long
    driver-class-name: com.mysql.jdbc.Driver
    #关闭默认模板引擎缓存
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  configuration:
    #开启驼峰命名规则
    map-underscore-to-camel-case: true
#  type-aliases-package: com.qzl.oamanages.shiro.entity
  #配置分页
  pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
logging:
  level:
    com:
      looedu:
        mapper: debug

